### ISSUE TITLE
Is defer commit.Free() necessary?

### ISSUE THREAD

**Issue by shinningstar** [libgit2/git2go#209]
The Object interface has a function called Free() which called libgit2 git_object_free(). Some test cases (  https://github.com/libgit2/git2go/blob/master/remote_test.go#L160) are using defer to call Free() function. However, in function allocObject, it has already used SetFinalizer to cal Free() function (https://github.com/libgit2/git2go/blob/master/object.go#L72).
So, I think the calling defer commit.Free() here is unnecessary, right?

Furthermore, when should I have to call Free() function explicitly?

**Comment by carlosmn** [comment]
The objects which git2go returns have the finalizer set so that the data from libgit2 is freed when the Go's garbage collector runs. That is, you never *have* to call the `Free()` methods yourself.

As libgit2 is using a different allocator from Go's runtime, the garbage collector does not know how much memory is being used by libgit2 data, which could lead to it not freeing up memory as aggressively as it could so in sutuations where memory is constrained, it might make sense to free the libgit2 data to free up OS resources; though I wouldn't expect this to make much of a difference outside of large blobs.

**Comment by shinningstar** [comment]
@carlosmn here: https://github.com/libgit2/git2go/blob/master/branch.go#L93
The implementation of CreateBranch() used new(Reference) does not set finalizer to free up resource. So I have to call Free() on the branch object returned from CreateBranch().
I think the implementation of Move() function is different because it used newReferenceFromC(). Should CreateBranch() need to change to use newReferenceFromC here?

**Comment by carlosmn** [comment]
`CreateBranch()` has a leak there, as it will never release the reference's memory, it should indeed use the constructor which takes care of it.
