### ISSUE TITLE
Unused parameter in OpenOndisk(parent *Config, path string)

### ISSUE THREAD

**Issue by TheDahv** [libgit2/git2go#256]
This is _very_ minor and low priority, but something I noticed as I was working on a personal project.

It seems as though `parent` has no bearing on the result of the function. Am I misinterpreting its intent or usage, or is this just fodder for code cleanup?

https://github.com/libgit2/git2go/blob/master/config.go#L329

**Comment by carlosmn** [comment]
It's quite possible this was a copy-paste error from `OpenLevel()` or a similar function. There is no parent here, since it's creating a new configuration object.

**Comment by praveentiru** [comment]
I would like to work  on this. But, I am bit confused.
The issue refers OpenOndisk which now at https://github.com/libgit2/git2go/blob/master/config.go#L346 rather than https://github.com/libgit2/git2go/blob/master/config.go#L329 where we have OpenLevel.

I will submit appropriate patch assuming that we want to clean-up OpenOndisk.

**Comment by carlosmn** [comment]
Fixed via #469
