### ISSUE TITLE
Compiling statically: libhttp_parser.so.2.1: cannot open shared object file

### ISSUE THREAD

**Issue by sithembiso** [libgit2/git2go#297]
I'm trying to build git2go statically, but it giving this error since it's looking for a dynamic library. I've been looking for the source code that will give me `libhttp_parser.so.2.1` (so I can compile it with other git2go dependencies) but I just can't find it anywhere. Any suggestions on where I can find the source code or remove this as a dependency?

**Comment by carlosmn** [comment]
I'm assuming that the error is happening because you're moving the resulting binary elsewhere. If this error does happen during linking, then whatever installed the http parser into your system has left it in a broken state and there's nothing we can do from here.

The libgit2 build system has found the parser in the system, so your package manager will tell you where it's from. If you're on a Debian derivative, the package is `libhttp_parser2.1`.

There is no way to remove the http parser as a dependency, but if it is not found on the system, libgit2 will use an in-tree version.

**Comment by Xiol** [comment]
@carlosmn Can this be made explicit in the documentation please? This stumped me for a long time. Ended up building a docker container to build the binary so it wouldn't link to the system libraries.

**Comment by sithembiso** [comment]
@Xiol I ended up putting this together: https://github.com/sithembiso/git2go-build
Hope it helps
