### ISSUE TITLE
Support libgit2 v0.25

### ISSUE THREAD

**Issue by avelino** [libgit2/git2go#359]
Homebrew upgrade: https://github.com/Homebrew/homebrew-core/commit/558ae83e40f59068be6bd4223d539ec58eee93a0

```
$ go get -u github.com/libgit2/git2go
# github.com/libgit2/git2go
../../libgit2/git2go/git.go:9:3: error: "Invalid libgit2 version; this git2go supports libgit2 v0.24"
# error "Invalid libgit2 version; this git2go supports libgit2 v0.24"
  ^
1 error generated.
```

**Comment by carlosmn** [comment]
The v0.25 series is supported in the v25 branch. You should always use a numbered branch, otherwise you're going to be surprised by this kind of change whenever there's a release.

Though master has been kept synchronized with the latest numbered branch, I'm likely going to change that, which is why this is not the case for moving to v25.
