### ISSUE TITLE
Clarifications on how to deal with static imports

### ISSUE THREAD

**Issue by nervo** [libgit2/git2go#464]
Hello,

i've struggled a lot before finding that in order to make use of statically linked libgit2 in a project importing git2go, the `static` tag must be used in command line.

for instance, in a main.go
```
package main

import (
	"github.com/libgit2/git2go"
...
)
...
```

one must build with:
```
go build --tags "static" main.go
```

Is this the "official" way ? Coud this be documented somewhere ?

**Comment by carlosmn** [comment]
The installation instructions https://github.com/libgit2/git2go#installing show which Makefile targets will run with the correct flags. If you're not installing it I suppose you might need to pass around the flags.

Dependency management in Go has changed quite a bit since this project started so it's quite possible it's not using the newest suggestions.

**Comment by nervo** [comment]
ok, thx for your answer :)
